export const SESSION_FILTERS = [
  { value: "VOCAL", label: "VOCAL", icon: "mic" },
  { value: "GUITAR", label: "GUITAR", icon: "guitar" },
  { value: "BASS", label: "BASS", icon: "bass" },
  { value: "DRUM", label: "DRUM", icon: "drum" },
  { value: "KEYBOARD", label: "KEYBOARD", icon: "keyboard" },
  { value: "ALL", label: "ALL", icon: "group" },
];

export const GENERATION_FILTERS = ["41ST", "40TH", "39TH", "OB"];

export const DEFAULT_SESSION = "VOCAL";
export const DEFAULT_GENERATION = "41ST";

export const MEMBERS = [
  {
    id: "kang-minji",
    name: "KANG MINJI",
    koreanName: "강민지",
    session: "VOCAL",
    generation: "41ST",
    position: "MAIN VOCAL",
    term: "2026 SPRING",
    birthday: "2003.04.12",
    department: "영어학과",
    mbti: "ENFP",
    image: null,
    intro: "무대를 뜨겁게 여는 메인 보컬.",
    quote: "첫 소절부터 관객이 고개를 들게 만드는 보컬이 되고 싶어요.",
    teams: ["Spring Live", "Queen Quatria"],
    tagline: "MAKE IT LOUD",
    isActive: true,
  },
  {
    id: "lee-junho",
    name: "LEE JUNHO",
    koreanName: "이준호",
    session: "GUITAR",
    generation: "41ST",
    position: "LEAD GUITAR",
    term: "2026 SPRING",
    birthday: "2002.09.18",
    department: "ELLT학과",
    mbti: "ISTP",
    image: null,
    intro: "거친 리프와 날카로운 톤을 책임지는 기타.",
    quote: "기타는 예쁘게 치는 것보다 정확히 찢고 들어가는 게 먼저예요.",
    teams: ["Spring Live", "Archive Session"],
    tagline: "RIFF ATTACK",
    isActive: true,
  },
  {
    id: "park-siwoo",
    name: "PARK SIWOO",
    koreanName: "박시우",
    session: "BASS",
    generation: "41ST",
    position: "BASS",
    term: "2026 SPRING",
    birthday: "2002.12.01",
    department: "영미문학문화학과",
    mbti: "INTP",
    image: null,
    intro: "묵직한 그루브로 중심을 잡는 베이스.",
    quote: "낮은 소리가 흔들리면 무대 전체가 흔들려요.",
    teams: ["Queen Quatria", "Club Night"],
    tagline: "LOW END",
    isActive: true,
  },
  {
    id: "choi-yerin",
    name: "CHOI YERIN",
    koreanName: "최예린",
    session: "DRUM",
    generation: "41ST",
    position: "DRUM",
    term: "2026 SPRING",
    birthday: "2003.06.22",
    department: "영어통번역학과",
    mbti: "ESTP",
    image: null,
    intro: "무대의 심장박동을 만드는 드러머.",
    quote: "박자는 지키고, 에너지는 끝까지 밀어붙입니다.",
    teams: ["Spring Live", "Drum Line"],
    tagline: "BREAK BEAT",
    isActive: true,
  },
  {
    id: "kim-dohyun",
    name: "KIM DOHYUN",
    koreanName: "김도현",
    session: "KEYBOARD",
    generation: "41ST",
    position: "KEYBOARD",
    term: "2026 SPRING",
    birthday: "2001.11.08",
    department: "국제학부",
    mbti: "INFJ",
    image: null,
    intro: "곡의 질감을 채우는 신스와 키보드.",
    quote: "빈 공간에 남는 잔향까지 설계하는 게 제 파트예요.",
    teams: ["Synth Lab", "Archive Session"],
    tagline: "NOISE WAVE",
    isActive: true,
  },
  {
    id: "yoo-sejin",
    name: "YOO SEJIN",
    koreanName: "유세진",
    session: "GUITAR",
    generation: "41ST",
    position: "RHYTHM GUITAR",
    term: "2026 SPRING",
    birthday: "2003.02.15",
    department: "영어교육과",
    mbti: "ENFJ",
    image: null,
    intro: "합주의 밀도를 끌어올리는 리듬 기타.",
    quote: "리듬 기타는 티 나지 않아도 밴드의 온도를 바꿉니다.",
    teams: ["Club Night", "Spring Live"],
    tagline: "STAY SHARP",
    isActive: true,
  },
  {
    id: "hwang-jaehyun",
    name: "HWANG JAEHYUN",
    koreanName: "황재현",
    session: "VOCAL",
    generation: "40TH",
    position: "VOCAL",
    term: "2025 SPRING",
    birthday: "2002.07.29",
    department: "영어학과",
    mbti: "ENTP",
    image: null,
    intro: "폭발적인 코러스로 무대를 밀어붙이는 보컬.",
    quote: "후렴에서 한 번 더 터지는 순간을 좋아합니다.",
    teams: ["40th Tribute", "Club Night"],
    tagline: "RED LINE",
    isActive: true,
  },
  {
    id: "seo-harin",
    name: "SEO HARIN",
    koreanName: "서하린",
    session: "BASS",
    generation: "39TH",
    position: "BASS",
    term: "2024 SPRING",
    birthday: "2001.03.03",
    department: "ELLT학과",
    mbti: "ISFP",
    image: null,
    intro: "탄탄한 루트와 침착한 사운드 메이커.",
    quote: "좋은 베이스라인은 과장하지 않아도 기억에 남아요.",
    teams: ["39th Session", "Archive Session"],
    tagline: "DEEP CUT",
    isActive: true,
  },
  {
    id: "oh-taeho",
    name: "OH TAEHO",
    koreanName: "오태호",
    session: "DRUM",
    generation: "OB",
    position: "DRUM",
    term: "2022 SPRING",
    birthday: "1999.10.21",
    department: "영미문학문화학과",
    mbti: "ESTJ",
    image: null,
    intro: "CRIMSON RED의 오래된 박자를 남긴 OB 드러머.",
    quote: "무대는 끝나도 박자는 후배들에게 남습니다.",
    teams: ["Alumni Stage", "1986 Night"],
    tagline: "OLD FLAME",
    isActive: false,
  },
];
